### ISSUE TITLE
Проблемка)

### ISSUE THREAD

**Issue by beliy1985** [turbulator/pandora-cas#1]
Ругается на службы!
Log:
```Invalid config for [script]: Service pandora-cas.lock does not match format <domain>.<name> for dictionary value @ data['script']['cross_lock']['sequence'][1]['service']. Got 'pandora-cas.lock' Service pandora-cas.start_engine does not match format <domain>.<name> for dictionary value @ data['script']['cross_engine_on']['sequence'][1]['service']. Got 'pandora-cas.start_engine' Service pandora-cas.stop_engine does not match format <domain>.<name> for dictionary value @ data['script']['cross_engine_off']['sequence'][1]['service']. Got 'pandora-cas.stop_engine' Service pandora-cas.unlock does not match format <domain>.<name> for dictionary value @ data['script']['cross_unlock']['sequence'][1]['service']. Got 'pandora-cas.unlock'. (See /config/configuration.yaml, line 137). Invalid config for [automation]: invalid template (TemplateSyntaxError: expected token 'end of print statement', got '_engine_temperature') for dictionary value @ data['action'][1]['data_template']['media_content_id']. Got None```

**Comment by beliy1985** [comment]
Еще ругается на автоматизации гдн используется темплэйт для сенсоров с цифрами:
```Invalid config for [automation]: invalid template (TemplateSyntaxError: expected token 'end of print statement', got '_engine_temperature') for dictionary value @ data['action'][1]['data_template']['media_content_id']. Got None.```

**Comment by beliy1985** [comment]
Для себя выход нашел, поправил домэйн, но надо сделать так в любом случае, а то службы нельзя использовать не в свитчах, не в скриптах

**Comment by turbulator** [comment]
Fixed in 0.2-beta
