### ISSUE TITLE
Как добавить второй автомобиль с другими учётными записями?

### ISSUE THREAD

**Issue by Daemon256** [turbulator/pandora-cas#10]
Есть два автомобиля и разные логины и пароли на сайт пандоры соответственно. Как можно добавить вторую учётную запись в HA 2021.12.5

**Comment by turbulator** [comment]
Привет! Пока это не предусмотрено. Поддерживается только подключение от одной учетной записи.

**Comment by Daemon256** [comment]
Вроде разобрался. По сути не требуется, т.к. на сайте пандоры можно добавить под одну учётку сколько угодно других.

**Comment by turbulator** [comment]
Нужно будет добавить в документацию этот момент. Спасибо!
