### ISSUE TITLE
Error - pandora_cas.start_engine

### ISSUE THREAD

**Issue by toxig** [turbulator/pandora-cas#17]
Сначала скажу большое спасибо! Интеграция супер. Пользуюсь больше года на Pandora UX4G.
Подружил с Алисой, часто завожу утром авто через команду колонке - "Алиса, заведи машину".

Проблема. После обновления интеграции на версию v2023.7.12 (на бета v2023.7.13 тоже) перестали работать вызов сервисов.

При старте HA в логах сыпятся ошибки:
`2023-09-05 02:00:35.713 ERROR (MainThread) [homeassistant.components.binary_sensor] Ignoring invalid device info: Invalid device info {'default_name': 'RAV4', 'identifiers': {('pandora_cas', '1077******')}, 'manufacturer': 'Pandora', 'model': 'UX-4G', 'sw_version': '1.81 / 1.23F375'} for 'pandora_cas' config entry: device info needs to either describe a device, link to existing device or provide extra information.`

Далее, при вызове сервисов (использую в автоматизациях)
```service: pandora_cas.stop_engine
data:
  device_id: 1077******
```
```
  service: pandora_cas.remote_command
  data:
    device_id: 1077******
    command_id: 1
```
Ловлю ошибку в GUI: `Unknown error`
В логах: `TypeError: 'PandoraCASUpdateCoordinator' object is not subscriptable`

При активация через switch кнопки интеграции (двигатель, охрана и т.д.) - все отлично работает. 
Не работают только сервисы.

Подробные логи во вложении - [Pandora Err logs.txt](https://github.com/turbulator/pandora-cas/files/12517240/Pandora.Err.logs.txt)

**Comment by turbulator** [comment]
Дружище, ты перепутал интеграцию. Судя по всему у тебя форк от @alryaz

**Comment by toxig** [comment]
> Дружище, ты перепутал интеграцию. Судя по всему у тебя форк от @alryaz

День добрый. Спасибо что подсветил!
Действительно, другая интеграция. 
https://github.com/alryaz/hass-pandora-cas

**Comment by alryaz** [comment]
@toxig Вылезло упоминание, попробуйте версию: https://github.com/alryaz/hass-pandora-cas/releases/tag/v2023.9.1

**Comment by toxig** [comment]
Решение - обновить на свежую версию интеграции. 
Перезапустить HA.
