### ISSUE TITLE
The method for providing platform translations has changed in Home Assistant Core

### ISSUE THREAD

**Issue by emontnemery** [turbulator/pandora-cas#18]
The method for providing platform translations has changed in Home Assistant Core, and this integration needs to be updated.

Details can be found in https://developers.home-assistant.io/blog/2024/03/05/platform_entity_translations_deprecation

**Comment by DJGLTD** [comment]
any update on this looks like the integration now doesn't work at all maybe @turbulator can provide an update?

**Comment by turbulator** [comment]
Roger that

**Comment by turbulator** [comment]
Fixed in 1.4.6
