### ISSUE TITLE
Problems with upgrade to 1.4.1

### ISSUE THREAD

**Issue by almazikv** [turbulator/pandora-cas#7]
After upgrade to 1.4.1 lost most of the sensors except device tracker and sim card balance. All others turned to unavailable.
Downgraded to 1.3 - sensors returned

**Comment by turbulator** [comment]
Please have a look on settings of integration and set up expire after parameter. 600 seconds will be enough.

But you are right. Default value should never expire. I'll fix it in 1.4.2

**Comment by turbulator** [comment]
Fixed
