### ISSUE TITLE
Management of the EXT channels.

### ISSUE THREAD

**Issue by denisapokin** [turbulator/pandora-cas#8]
EXT channels do not work. Channels work from the Pandora app. Maybe I'm doing something wrong, or how is it redefined channels that need to be managed? CAS DXL 4710

**Comment by turbulator** [comment]
Please describe in details what exactly do you doing. Also please have a look on my drive2 post: https://www.drive2.ru/l/526540176697066100/

**Comment by turbulator** [comment]
Turn on (off) external channel in app or website will be converted to GSM 456 (654). These events (GSM 456 and GSM 654) you should use in Alarm Studio as triggers for external channel.

**Comment by turbulator** [comment]
@denisapokin, have you got any result?
